blank_issues_enabled: false
contact_links:
  - name: Questions or Feedback
    url: https://github.com/pipeabellos/thetoolforthat/discussions
    about: For questions or general feedback, start a discussion
